# Generated by Django 6.0.6 on 2026-06-07 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customerprofile_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='Name must contain only Persian letters', regex='^[\\u0600-\\u06FF\\s]+$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 10 digits', regex='^\\d{10}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=1, max_length=13, validators=[django.core.validators.RegexValidator(message=' phone number must be in format +989********* ', regex='^\\+989\\d{9}$')]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
