# Generated by Django 5.2.14 on 2026-05-06 16:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Name must contain only Persian letters', regex='^[\\u0600-\\u06FF\\s]+$')])),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message=' phone number must be in format +989********* ', regex='^\\+989\\d{9}$')])),
                ('national_id', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='National ID must be exactly 10 digits', regex='^\\d{10}$')])),
            ],
        ),
    ]
